server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  client:
    # ????????? ??????????? ?????? Eureka Server ? ???????
    registerWithEureka: false
    fetchRegistry: false
